//uploading
export const UPLOADING_START = 'UPLOADING_START';
export const UPLOADING_SUCCESS = 'UPLOADING_SUCCESS';
export const UPLOADING_FAIL = 'UPLOADING_FAIL';
export const UPLOADING = 'UPLOADING';

export const GET_DATA = 'GET_DATA';

export const UPDATE_PROFILE_IMG_URL = 'UPDATE_PROFILE_IMG_URL';

//rooms
export const FETCH_ROOMS_REQUEST = 'FETCH_ROOMS_REQUEST';
export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOMS_EMPTY = 'FETCH_ROOMS_EMPTY';

export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';

export const SEARCH_ROOM_REQUEST = 'SEARCH_ROOM_REQUEST';
export const SEARCH_ROOM_SUCCESS = 'SEARCH_ROOM_SUCCESS';

export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';

export const ADD_ROOM_REQUEST = 'ADD_ROOM_REQUEST';
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';

export const CHANGE_ROOM_REQUEST = 'CHANGE_ROOM_REQUEST';

export const EXIT_ROOM_REQUEST = 'EXIT_ROOM_REQUEST';
export const LEAVE_CHAT_REQUEST = 'LEAVE_CHAT_REQUEST';

export const MAKE_ROOM_PUBLIC = 'MAKE_ROOM_PUBLIC';

export const ERROR_CATCHED = 'ERROR_CATCHED';

//messaging
export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
