export const UPLOADING_START = 'UPLOADING_START';
export const UPLOADING_SUCCESS = 'UPLOADING_SUCCESS';
export const UPLOADING_FAIL = 'UPLOADING_FAIL';
export const UPLOADING = 'UPLOADING';

export const GET_DATA = 'GET_DATA';

export const UPDATE_PROFILE_IMG_URL = 'UPDATE_PROFILE_IMG_URL';
